---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: po1-nextjs
spec:
  template:
    spec:
      containers:
      - name: po1-nextjs
        env:
        - name: ENV_TYPE
          value: "production"
        - name: PAYPAL_URL
          value: "production.paypal.com"
        - name: DB_USER
          value: "prod_username"
        - name: DB_PASSWORD
          value: "prod_password"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080

