---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: po1-nextjs
spec:
  template:
    spec:
      containers:
      - name: po1-nextjs
        env:
        - name: ENV
          value: "prod-us"
        - name: GPU_ENABLED
          value: "1"
