---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: po1-nextjs
spec:
  template:
    spec:
      containers:
      - name: po1-nextjs
        env:
        - name: UI_THEME
          value: "dark"
        - name: CACHE_SIZE
          value: "1024kb"
        - name: PAGE_LIMIT
          value: "25"
        - name: SORTING
          value: "ascending"
        - name: N_BUCKETS
          value: "42"