---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: po1-gateway-sqs
  namespace: po1
spec:
  scaleTargetRef:
    name: po1-gateway
  minReplicaCount: 1
  maxReplicaCount: 5
  pollingInterval: 10
  cooldownPeriod:  30
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: po1-keda-sqs-credentials
    metadata:
      queueURL: https://sqs.eu-west-1.amazonaws.com/236731556556/po1-k8-sqs-test.fifo
      queueLength: 2
      awsRegion: eu-west-1
      identityOwner: operator
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: po1-gateway-sqs
  namespace: po1
spec:
  podIdentity:
    provider: aws-eks
