apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qa
namePrefix: qa-eu-

resources:
- ../../base

components:
  - ../../variants/qa
  - ../../variants/eu

patchesStrategicMerge:
- deployment.yml
- version.yml
- replicas.yml
- settings.yml
